#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install
# You can use an ENV variable by using $(ENV_VAR_NAME) as the value

# ---------------------------------------------------------------------
# Title of this site
# ---------------------------------------------------------------------

title: ${W_TITLE:-Wiki}

# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: ${W_HOST:-http://localhost}

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: ${W_PORT:-80}

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ${W_REPO_PATH:-./repo}
  data: ${W_DATA_PATH:-./data}

# ---------------------------------------------------------------------
# Upload Limits
# ---------------------------------------------------------------------
# In megabytes (MB}

uploads:
  maxImageFileSize: ${W_MAX_IMAGE_FILE_SIZE:-3}
  maxOtherFileSize: ${W_MAX_OTHER_FILE_SIZE:-100}

# ---------------------------------------------------------------------
# Site Language
# ---------------------------------------------------------------------
# Possible values: en, de, es, fa, fr, ja, ko, nl, pt, ru, sr, sv, tr or zh

lang: ${W_LANG:-en}

# Enable for right to left languages (e.g. arabic):
langRtl: ${W_LANG_RTL:-false}

# ---------------------------------------------------------------------
# Site Authentication
# ---------------------------------------------------------------------

public: ${W_PUBLIC_ACCESS:-false}

auth:
  defaultReadAccess: ${W_AUTH_DEFAULT_READ_ACCESS:-false}
  local:
    enabled: ${W_AUTH_LOCAL:-true}
  google:
    enabled: ${W_AUTH_GOOGLE:-false}
    clientId: ${W_AUTH_GG_CLIENT_ID}
    clientSecret: ${W_AUTH_GG_CLIENT_SECRET}
  microsoft:
    enabled: ${W_AUTH_MICROSOFT:-false}
    clientId: ${W_AUTH_MS_CLIENT_ID}
    clientSecret: ${W_AUTH_MS_CLIENT_SECRET}
  facebook:
    enabled: ${W_AUTH_FACEBOOK:-false}
    clientId: ${W_AUTH_FB_CLIENT_ID}
    clientSecret: ${W_AUTH_FB_CLIENT_SECRET}
  github:
    enabled: ${W_AUTH_GITHUB:-false}
    clientId: ${W_AUTH_GH_CLIENT_ID}
    clientSecret: ${W_AUTH_GH_CLIENT_SECRET}
  slack:
    enabled: ${W_AUTH_SLACK:-false}
    clientId: ${W_AUTH_SK_CLIENT_ID}
    clientSecret: ${W_AUTH_CLIENT_SECRET}
  ldap:
    enabled: ${W_AUTH_LDAP:-false}
    url: ${W_AUTH_LDAP_URL}
    bindDn: ${W_AUTH_LDAP_BIND_DN}
    bindCredentials: ${W_AUTH_LDAP_BIND_CREDENTIALS}
    searchBase: ${W_AUTH_LDAP_SEARCH_BASE}
    searchFilter: ${W_AUTH_LDAP_SEARCH_FILTER}
    tlsEnabled: ${W_AUTH_LDAP_TLS_ENABLE}
    tlsCertPath: ${W_AUTH_LDAP_TLS_CERT_PATH}
  azure:
    enabled: ${W_AUTH_AZURE:-false}
    clientId: ${W_AUTH_AZ_CLIENT_ID}
    clientSecret: ${W_AUTH_AZ_CLIENT_SECRET}
    resource: ${W_AUTH_AZ_RESOURCE}
    tenant: ${W_AUTH_AZ_TENANT}
  oauth2:
    enabled: ${W_AUTH_OAUTH2:-false}
    clientId: ${W_AUTH_OH_CLIENT_ID}
    clientSecret: ${W_AUTH_OH_CLIENT_SECRET}
    authorizationURL: ${W_AUTH_OH_AUTHORIZATION_URL}
    tokenURL: ${W_AUTH_OH_TOKEN_URL}
  oidc:
    enabled: ${W_AUTH_OIDC:-false}
    clientId: ${W_AUTH_OC_CLIENT_ID}
    clientSecret: ${W_AUTH_OC_CLIENT_SECRET}
    issuer: ${W_AUTH_OC_ISSUER}
    userInfoUrl: ${W_AUTH_OC_USER_INFO_URL}
    authorizationURL: ${W_AUTH_OC_AUTHORIZATION_URL}
    tokenURL: ${W_AUTH_OC_TOKEN_URL
    emailClaim: ${W_AUTH_OC_EMAIL_CLAIM}
    usernameClaim: ${W_AUTH_OC_USERNAME_CLAIM}
# ---------------------------------------------------------------------
# Secret key to use when encrypting sessions
# ---------------------------------------------------------------------
# Use a long and unique random string (256-bit keys are perfect!)

sessionSecret: ${W_SESSION_SECRET:-1234567890abcdefghijklmnopqrstuvxyz}

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------

db: ${W_DB_CONNECTION_STRING:-mongodb://localhost:27017/wiki}

# ---------------------------------------------------------------------
# Git Connection Info
# ---------------------------------------------------------------------

git: ${W_GIT_ENABLE:-false}
  url: ${W_GH_URL}
  branch: ${W_GH_BRANCH}
  auth:

    # Type: basic or ssh
    type: ${W_GH_AUTH_TYPE:-ssh}

    # Only for Basic authentication:
    username: ${W_GH_USERNAME}
    password: ${W_GH_PASSWORD}

    # Only for SSH authentication:
    privateKey: ${W_GH_PRIVATE_KEY_PATH}

    sslVerify: ${W_GH_SSL_VERIFY:-true}

  # Default email to use as commit author
  serverEmail: ${W_GH_SERVER_EMAIL}

  # Whether to use user email as author in commits
  showUserEmail: ${W_GH_SHOW_USER_EMAIL:-true}

# ---------------------------------------------------------------------
# Features
# ---------------------------------------------------------------------
# You can enable / disable specific features below

features:
  linebreaks: ${W_FT_LINE_BREAKS:-true}
  mathjax: ${W_FT_MATHJAX:-true}

# ---------------------------------------------------------------------
# External Logging
# ---------------------------------------------------------------------

externalLogging:
  bugsnag: ${W_EL_BUGSNAG_ENABLE:-false}
  loggly: ${W_EL_LOGGLY_ENABLE:-false}
  papertrail: ${W_EL_PAPERTRAIL_ENABLE:-false}
  rollbar: ${W_EL_ROLLBAR_ENABLE:-false}
  sentry: ${W_EL_SENTRY_ENABLE:-false}

# ---------------------------------------------------------------------
# Color Theme
# ---------------------------------------------------------------------

theme:
  primary: ${W_THEME_PRIMARY:-indigo}
  alt: ${W_THEME_ALT:-blue-grey}
  viewSource: ${W_THEME_VIEWSOURCE:-all}
  footer: ${W_THEME_FOOTER:-blue-grey}
  code:
    dark: ${W_THEME_CODE_ENABLE:-true}
    colorize: ${W_THEME_COLORIZE_ENABLE:-true}

#